config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#main'

  resources :articles
  resources :movies
  resources :actors
  resources :reviews
  resources :comments

  post 'actors/:id' => 'actors#add_movie', as: :add_movie

  delete 'actors/delete_movie/:id' => 'actors#delete_movie', as: :delete_movie

  post 'movies/:id' => 'movies#add_actor'

  delete 'movies/delete_actor/:id' => 'movies#delete_actor', as: :delete_actor

  post 'articles/up_vote/:id' => 'articles#up_vote'
  post 'articles/down_vote/:id' => 'articles#down_vote'

  post 'movies/up_vote/:id' => 'movies#up_vote'
  post 'movies/down_vote/:id' => 'movies#down_vote'

  post 'reviews/up_vote' => 'reviews#up_vote'
  post 'reviews/down_vote' => 'reviews#down_vote'

  get 'search' => 'search#search', as: :search

  get 'search_movie_list' => 'actors#movie_select_list', as: :movie_search_list
  get 'search_actor_list' => 'movies#actor_select_list', as: :actor_search_list

  get 'movie_list/:id' => 'actors#movie_list', as: :movie_list
  get 'actor_list/:id' => 'movies#actor_list', as: :actor_list
  get 'review_list/:id' => 'movies#review_list', as: :review_list
  get 'comment_list/:id' => 'comments#comments_list', as: :comment_list

  get '/:anything', to: "application#error_404", constraints: { anything: /.*/ }

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  has_and_belongs_to_many :movies, -> { uniq }, dependent: :destroy

  validates :name, :age, :photo_url, presence: true

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments, :dependent => :destroy

  validates :title, :body, :img_url, presence: true

end

app/models/article_rating.rb
class ArticleRating < ActiveRecord::Base

  belongs_to :user

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :article
  belongs_to :review

  validates :body, presence: true


end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :actors, -> { uniq }, dependent: :destroy

  validates :name, :genre, :box_office, :desc, :poster_url, presence: true

  def calculate_ball

	  	r_count = 0
	  	reviews.map {|r| r_count+=1 } 
		total_ball = reviews.map(&:total_ball).inject(:+) 
			
		if total_ball	
			total_ball = total_ball / r_count
		end
			
  end

end

app/models/movie_rating.rb
class MovieRating < ActiveRecord::Base

  belongs_to :user

end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :users

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie
  has_many :comments, dependent: :destroy

  validates :title, :body, presence: true

end

app/models/review_rating.rb
class ReviewRating < ActiveRecord::Base

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, -> {uniq}, dependent: :destroy
  has_many :ratings, dependent: :destroy

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	add_breadcrumb "Home", :root_path

	def search
		@articles = Article.limit(20).ransack(title_cont: params[:search]).result
		@actors = Actor.limit(20).ransack(name_cont: params[:search]).result
		@reviews = Review.limit(20).ransack(title_cont: params[:search]).result
		@movies = Movie.limit(20).ransack(name_cont: params[:search]).result
		add_breadcrumb "Search result"
	end
		
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artcile_helper.rb
module ArtcileHelper
end

app/helpers/artciles_helper.rb
module ArtcilesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.haml
- if !@articles.empty?
  %h1 
    Articles
  %table.table.table-hover
    %tr
      %th
        Title
      %th
        Picture
      %th
        Rating
      %th
        Comments      
    - @articles.each do |a|
      %tr
        %td
          = link_to "#{a.title}", article_path(a)
        %td
          = image_tag(a.img_url, size: "50x50") 
        %td
          = a.rating        
        %td
          = a.comments.count  

- if !@movies.empty?
  %h1 
    Movies
  %table.table.table-hover
    %tr
      %th
        Name
      %th
        Picture
      %th
        Rating
      %th
        Reviews      
    - @movies.each do |m|
      %tr
        %td
          = link_to "#{m.name}", movie_path(m)
        %td
          = image_tag(m.poster_url, size: "50x50") 
        %td
          = m.rating        
        %td
          = m.reviews.count          

- if !@reviews.empty?
  %h1 
    Reviews
  %table.table.table-hover
    %tr
      %th
        Title
      %th  
        Rating
      %th
        Comments      
    - @reviews.each do |r|
      %tr
        %td
          = link_to "#{r.title}", review_path(r)
        %td
          = r.rating        
        %td
          = r.comments.count  

- if !@actors.empty?
  %h1 
    Actors
  %table.table.table-hover
    %tr
      %th
        Name
      %th
        Photo
      %th
        Age
    - @actors.each do |a|
      %tr
        %td
          = link_to "#{a.name}", actor_path(a)
        %td
          = image_tag(a.photo_url, size: "50x50") 
        %td
          = a.age  