config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#main'

  resources :articles
  resources :movies
  resources :actors
  resources :reviews
  resources :comments

  post 'actors/:id' => 'actors#add_movie', as: :add_movie

  delete 'actors/delete_movie/:id' => 'actors#delete_movie', as: :delete_movie

  post 'movies/:id' => 'movies#add_actor'

  delete 'movies/delete_actor/:id' => 'movies#delete_actor', as: :delete_actor

  post 'articles/up_vote/:id' => 'articles#up_vote'
  post 'articles/down_vote/:id' => 'articles#down_vote'

  post 'movies/up_vote/:id' => 'movies#up_vote'
  post 'movies/down_vote/:id' => 'movies#down_vote'

  post 'reviews/up_vote' => 'reviews#up_vote'
  post 'reviews/down_vote' => 'reviews#down_vote'

  get 'search' => 'search#search', as: :search

  get 'search_movie_list' => 'actors#movie_select_list', as: :movie_search_list
  get 'search_actor_list' => 'movies#actor_select_list', as: :actor_search_list

  get 'movie_list/:id' => 'actors#movie_list', as: :movie_list
  get 'actor_list/:id' => 'movies#actor_list', as: :actor_list
  get 'review_list/:id' => 'movies#review_list', as: :review_list
  get 'comment_list/:id' => 'comments#comments_list', as: :comment_list

  get '/:anything', to: "application#error_404", constraints: { anything: /.*/ }

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  has_and_belongs_to_many :movies, -> { uniq }, dependent: :destroy

  validates :name, :age, :photo_url, presence: true

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments, :dependent => :destroy

  validates :title, :body, :img_url, presence: true

end

app/models/article_rating.rb
class ArticleRating < ActiveRecord::Base

  belongs_to :user

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :article
  belongs_to :review

  validates :body, presence: true


end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :actors, -> { uniq }, dependent: :destroy

  validates :name, :genre, :box_office, :desc, :poster_url, presence: true

  def calculate_ball

	  	r_count = 0
	  	reviews.map {|r| r_count+=1 } 
		total_ball = reviews.map(&:total_ball).inject(:+) 
			
		if total_ball	
			total_ball = total_ball / r_count
		end
			
  end

end

app/models/movie_rating.rb
class MovieRating < ActiveRecord::Base

  belongs_to :user

end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :users

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie
  has_many :comments, dependent: :destroy

  validates :title, :body, presence: true

end

app/models/review_rating.rb
class ReviewRating < ActiveRecord::Base

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, -> {uniq}, dependent: :destroy
  has_many :ratings, dependent: :destroy

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :check_in, except: [:destroy, :create, :up_vote, :down_vote, :main, :show]
  before_action :rating_check, only: [:up_vote, :down_vote]

  before_action :find_article, only: [:show, :destroy, :edit, :update]

  add_breadcrumb "Home", :root_path

  def show
    @comment = Comment.new
    @comments = @article.comments.paginate(:page => params[:page], :per_page => 10)
    add_breadcrumb "#{@article.title}"
  end

  def new
    @article = Article.new
    add_breadcrumb "New article"
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_url
    else
      render "new"
    end
  end

  def destroy
    if @article.destroy
      redirect_to root_url
    end
  end

  def main
    @articles = Article.order('id DESC')
    @articles = @articles.paginate(:page => params[:page], :per_page => 3)
  end

  def edit
    add_breadcrumb "Edit article"
  end

  def update
    if @article.update(article_params)
      redirect_to root_url
    end
  end

  def up_vote
    if @rating.article_rating == "down"
      @rating.article_rating = nil
      change_rating(@rating, "up")
      redirect_to(:back)
    elsif @rating.article_rating == "up"
      redirect_to(:back)
    elsif  @rating.article_rating.nil?
      @rating.article_rating = "up"
      change_rating(@rating, "up")
      redirect_to(:back)
    end
  end

  def down_vote
    if @rating.article_rating == "down"
      redirect_to(:back)
    elsif @rating.article_rating == "up"
      @rating.article_rating = nil
      change_rating(@rating, "down")
      redirect_to(:back)
    elsif  @rating.article_rating.nil?
      @rating.article_rating = "down"
      change_rating(@rating, "down")
      redirect_to(:back)
    end
  end

  private

  def check_in
    if current_user
      redirect_to new_user_session_path unless current_user.admin?
    else
      redirect_to new_user_session_path
    end
  end

  def article_params
    params.require(:article).permit(:title, :body, :img_url)
  end

  def change_rating(rating, direction)
    rating.save
    @article = Article.find(params[:id])
    if direction == "up"
      @article.rating += 1
    elsif direction == "down"
      @article.rating -= 1
    end
    @article.save
  end

  def rating_check
    id = params[:id]
    if current_user.ratings.where(post_id: id).empty?
      @rating = current_user.ratings.create(post_id: id)
      @rating.post_id = id
      @rating.save
    else
      @rating = current_user.ratings.find_by(post_id: id)
    end
  end

  def find_article
    @article = Article.find(params[:id])
  end  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home

  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artcile_helper.rb
module ArtcileHelper
end

app/helpers/artciles_helper.rb
module ArtcilesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/_admin_panel.html.haml
%h3 Hello, admin!
%ul
  %li
    = link_to "Create article", new_article_path
  %li
    = link_to "Create movie", new_movie_path
  %li
    = link_to "Create actor", new_actor_path

app/views/articles/_user_panel.html.haml
%h4
  Hello
  = current_user.email

app/views/articles/edit.html.haml
.container
  .row
    .col-md-6.col-md-offset-1
      .jumbotron
        %h1 Edit article

        = bootstrap_form_for @article do |f|
          = f.text_field :title
          = f.text_area :body
          = f.text_field :img_url
          = f.submit "Update"

app/views/articles/main.html.haml
- @articles.each do |a|
  
  .article  
    .center
      = image_tag(a.img_url, size: "600x400")
    .caption
      %h2
        .title
          = link_to "#{a.title}", article_path(a)
        - if current_user
          - if current_user.admin?
            = link_to "EDIT", edit_article_path(a), class: "btn btn-default"
            = link_to "DELETE", a, method: :delete, class: "btn btn-danger"
      %p
        = a.body
      .btn-group
        = link_to "#{a.comments.count} Comments", article_path(a), class: "btn btn-default"
        %button.btn.btn-info#rating{:value => a.rating}
          Rating
          .badge
            = a.rating
      .btn-group
        - if current_user
          - if current_user.ratings.find_by(post_id: a.id)
            - if current_user.ratings.find_by(post_id: a.id).article_rating == "down" || current_user.ratings.find_by(post_id: a.id).article_rating.nil?
              = link_to "+", {:controller => "articles", :action => "up_vote", :id => a.id}, method: :post, class: "btn btn-default"
            - if current_user.ratings.find_by(post_id: a.id).article_rating == "up" || current_user.ratings.find_by(post_id: a.id).article_rating.nil?
              = link_to "-", {:controller => "articles", :action => "down_vote", :id => a.id}, method: :post, class: "btn btn-default"
          - else     
            = link_to "+", {:controller => "articles", :action => "up_vote", :id => a.id}, method: :post, class: "btn btn-default"
            = link_to "-", {:controller => "articles", :action => "down_vote", :id => a.id}, method: :post, class: "btn btn-default"
      .post-data
        = a.created_at.strftime("%d %b. %Y")
        = a.created_at.strftime("%H:%M")
      %hr
.center
  = will_paginate @articles, renderer: BootstrapPagination::Rails 

app/views/articles/new.html.haml
.container
  .row
    .col-md-6.col-md-offset-1
      .jumbotron
        %h1 New article

        = bootstrap_form_for @article do |f|
          = f.text_field :title
          = f.text_area :body
          = f.text_field :img_url
          = f.submit "Create"

app/views/articles/show.html.haml
.center
  = image_tag(@article.img_url, size: "600x400")
.caption
  %h2
    = @article.title
    - if current_user
      - if current_user.admin?
        = link_to "EDIT", edit_article_path(@article), class: "btn btn-default"
        = link_to "DEL", @article, method: :delete, class: "btn btn-danger" 
  %p
    = @article.body
  %button.btn.btn-info
    Rating
    .badge
      = @article.rating
  .btn-group
    - if current_user
      - if current_user.ratings.find_by(post_id: @article.id)
        - if current_user.ratings.find_by(post_id: @article.id).article_rating == "down" || current_user.ratings.find_by(post_id: @article.id).article_rating.nil?
          = link_to "+", {:controller => "articles", :action => "up_vote", :id => @article.id}, method: :post, class: "btn btn-default"
        - if current_user.ratings.find_by(post_id: @article.id).article_rating == "up" || current_user.ratings.find_by(post_id: @article.id).article_rating.nil?
          = link_to "-", {:controller => "articles", :action => "down_vote", :id => @article.id}, method: :post, class: "btn btn-default"
      - else     
        = link_to "+", {:controller => "articles", :action => "up_vote", :id => @article.id}, method: :post, class: "btn btn-default"
        = link_to "-", {:controller => "articles", :action => "down_vote", :id => @article.id}, method: :post, class: "btn btn-default"    
  .post-data
    = @article.created_at.strftime("%d %b. %Y")
    = @article.created_at.strftime("%H:%M")
  
%hr

= render "comments/index", comments: @comments

- if current_user
  %h3 New comment
  = bootstrap_form_for @comment do |f|
    = f.text_area :body
    = f.hidden_field :article_id, :value => @article.id
    = f.hidden_field :user_id, :value => current_user.id
    = f.submit