config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#main'

  resources :articles
  resources :movies
  resources :actors
  resources :reviews
  resources :comments

  post 'actors/:id' => 'actors#add_movie', as: :add_movie

  delete 'actors/delete_movie/:id' => 'actors#delete_movie', as: :delete_movie

  post 'movies/:id' => 'movies#add_actor'

  delete 'movies/delete_actor/:id' => 'movies#delete_actor', as: :delete_actor

  post 'articles/up_vote/:id' => 'articles#up_vote'
  post 'articles/down_vote/:id' => 'articles#down_vote'

  post 'movies/up_vote/:id' => 'movies#up_vote'
  post 'movies/down_vote/:id' => 'movies#down_vote'

  post 'reviews/up_vote' => 'reviews#up_vote'
  post 'reviews/down_vote' => 'reviews#down_vote'

  get 'search' => 'search#search', as: :search

  get 'search_movie_list' => 'actors#movie_select_list', as: :movie_search_list
  get 'search_actor_list' => 'movies#actor_select_list', as: :actor_search_list

  get 'movie_list/:id' => 'actors#movie_list', as: :movie_list
  get 'actor_list/:id' => 'movies#actor_list', as: :actor_list
  get 'review_list/:id' => 'movies#review_list', as: :review_list
  get 'comment_list/:id' => 'comments#comments_list', as: :comment_list

  get '/:anything', to: "application#error_404", constraints: { anything: /.*/ }

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  has_and_belongs_to_many :movies, -> { uniq }, dependent: :destroy

  validates :name, :age, :photo_url, presence: true

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments, :dependent => :destroy

  validates :title, :body, :img_url, presence: true

end

app/models/article_rating.rb
class ArticleRating < ActiveRecord::Base

  belongs_to :user

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :article
  belongs_to :review

  validates :body, presence: true


end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :actors, -> { uniq }, dependent: :destroy

  validates :name, :genre, :box_office, :desc, :poster_url, presence: true

  def calculate_ball

	  	r_count = 0
	  	reviews.map {|r| r_count+=1 } 
		total_ball = reviews.map(&:total_ball).inject(:+) 
			
		if total_ball	
			total_ball = total_ball / r_count
		end
			
  end

end

app/models/movie_rating.rb
class MovieRating < ActiveRecord::Base

  belongs_to :user

end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :users

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie
  has_many :comments, dependent: :destroy

  validates :title, :body, presence: true

end

app/models/review_rating.rb
class ReviewRating < ActiveRecord::Base

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, -> {uniq}, dependent: :destroy
  has_many :ratings, dependent: :destroy

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :rating_check, only: [:up_vote, :down_vote]
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Movies", :movies_path

  before_action :if_admin, only: [:new, :edit, :destroy]

  def index
    @movies = Movie.all
    @movies = @movies.paginate(:page => params[:page], :per_page => 8)
  end

  def new
    @movie = Movie.new
    add_breadcrumb "New movie"
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else 
      render 'new'
    end
  end

  def show
    @movie = Movie.find(params[:id])
    total_ball = @movie.calculate_ball
    @movie.total_ball = total_ball
    @actors = @movie.actors.limit(5)
    @reviews = @movie.reviews.limit(5)
    add_breadcrumb "#{@movie.name}"
  end

  def edit
    @movie = Movie.find(params[:id])
    add_breadcrumb "Edit movie"
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(params[:id])
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to movies_url
    end
  end

  def add_actor
    actor_id = params[:id]
    @movie = Movie.find(params[:movie_id])
    @movie.actors << Actor.find(actor_id)
    redirect_to movie_path(@movie)
  end

  def delete_actor
    actor_id = params[:actor_id]
    @movie = Movie.find(params[:id])
    @movie.actors.delete(actor_id)
    redirect_to movie_path(@movie)
  end

  def up_vote
    if @rating.movie_rating == "down"
      @rating.movie_rating = nil
      change_rating(@rating, "up")
      redirect_to(:back)
    elsif @rating.movie_rating == "up"
      redirect_to(:back)
    elsif  @rating.movie_rating.nil?
      @rating.movie_rating = "up"
      change_rating(@rating, "up")
      redirect_to(:back)
    end
  end

  def down_vote
    if @rating.movie_rating == "down"
      redirect_to(:back)
    elsif @rating.movie_rating == "up"
      @rating.movie_rating = nil
      change_rating(@rating, "down")
      redirect_to(:back)
    elsif  @rating.movie_rating.nil?
      @rating.movie_rating = "down"
      change_rating(@rating, "down")
      redirect_to(:back)
    end
  end

  def actor_select_list
    @actors = Actor.ransack(name_cont: params[:actor_name]).result
    @actors = @actors.limit(20)
  end

  def actor_list
    @actors = Movie.find(params[:id]).actors
    @actors = @actors.paginate(:page => params[:page], :per_page => 15)
  end

  def review_list
    @reviews = Movie.find(params[:id]).reviews
    @reviews = @reviews.paginate(:page => params[:page], :per_page => 15)
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :movie, :genre, :box_office, :poster_url, :desc, :rating)
  end

  def rating_check
    id = params[:id]
    if current_user.ratings.where(post_id: id).empty?
      @rating = current_user.ratings.create
      @rating.post_id = id
      @rating.save
    else
      @rating = current_user.ratings.find_by(post_id: id)
    end
  end

  def change_rating(rating, direction)
    rating.save
    movie = Movie.find(params[:id])
    if direction == "up"
      movie.rating += 1
    elsif direction == "down"
      movie.rating -= 1
    end
    movie.save
  end

  def if_admin
    if current_user
      if !current_user.admin?
        redirect_to root_path
      end  
    else
      redirect_to root_path
    end     
  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artcile_helper.rb
module ArtcileHelper
end

app/helpers/artciles_helper.rb
module ArtcilesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/movies/_index.html.haml
%hr
  %table.table.table-hover.short-list
    %th Poster
    %th Title
    %th Box office
    %th Actors
    %th Genre
    %th Rating
    - movies.each do |m|
      %tr
        %td
          = image_tag(m.poster_url, size: "100x150")
        %td
          = m.name
        %td    
          %p
            = m.box_office
        %td    
          %p
            - m.actors.limit(3).each do |a|
              = link_to "#{a.name}", actor_path(a)  
            = link_to "...", movie_path(m)    
        %td    
          %p
            = m.genre
        %td  
          %p
            Rating:
            = m.rating
            
.center
  .panel.panel-default
    = will_paginate movies, renderer: BootstrapPagination::Rails 

app/views/movies/_short_list.html.haml
%hr
  %table.table.table-hover.short-list
    %th Poster
    %th Title
    %th Box office
    %th Actors
    %th Genre
    %th Rating
    - movies.each do |m|
      %tr
        %td
          = image_tag(m.poster_url, size: "100x150")
        %td
          = m.name
        %td    
          %p
            = m.box_office
        %td    
          %p
            - m.actors.limit(3).each do |a|
              = link_to "#{a.name}", actor_path(a)  
            = link_to "...", movie_path(m)    
        %td    
          %p
            = m.genre
        %td  
          %p
            Rating:
            = m.rating
            
.center
  .panel.panel-default
    = will_paginate movies, renderer: BootstrapPagination::Rails 

app/views/movies/actor_list.html.haml
.center
  .panel.panel-default
    = will_paginate @actors

- if !@actors.empty?
  %h1 
    Actors
  %table.table.table-hover
    %tr
      %th
        Name
      %th
        Photo
      %th
        Age
    - @actors.each do |a|
      %tr
        %td
          = link_to "#{a.name}", actor_path(a)
        %td
          = image_tag(a.photo_url, size: "50x50") 
        %td
          = a.age  

app/views/movies/actor_select_list.html.haml
- unless @actors.empty?
  %h1 
    Actors
  %table.table.table-hover
    %tr
      %th
        Name
      %th
        Photo
      %th
        Age
      %th
        Option  
    - @actors.each do |a|
      %tr
        %td
          = link_to "#{a.name}", actor_path(a)
        %td
          = image_tag(a.photo_url, size: "70x100") 
        %td
          = a.age  
        %td
          = link_to "Select", {:controller => "movies", :action => "add_actor", :id => a.id, :movie_id => params[:movie_id]}, method: :post, class: "btn btn-info"

app/views/movies/edit.html.haml
.container
  .row
    .col-md-5.col-md-offset-3
      .jumbotron

        %h1 New movie
        = bootstrap_form_for @movie do |f|
          = f.text_field :name
          = f.text_field :box_office
          = f.text_area :desc
          = f.text_field :poster_url
          = f.submit "Update"

app/views/movies/index.html.haml
- @movies.each do |m|
  .col-md-6
    %h3
      =m.name
      - if current_user
        - if current_user.admin?
          .btn-group
            = link_to "EDIT", edit_movie_path(m), class: "btn btn-default"
            = link_to "DEL", m, method: :delete, class: "btn btn-danger"
    .poster
      =image_tag(m.poster_url, size: "120x200")
    %p
      Box office:
      = m.box_office
    %p
      Actors:
      - m.actors.limit(3).each do |a|
        = link_to "#{a.name}", actor_path(a)  
      = link_to "...", movie_path(m)    
    %p
      Genre:
      = m.genre
    %p
      Rating:
      = m.rating
    .btn-group 
      - if current_user
        - if current_user.ratings.find_by(post_id: m.id)
          - if current_user.ratings.find_by(post_id: m.id).movie_rating == "down" || current_user.ratings.find_by(post_id: m.id).movie_rating.nil?
            = link_to "+", {:controller => "movies", :action => "up_vote", :id => m.id}, method: :post, class: "btn btn-default"
          - if current_user.ratings.find_by(post_id: m.id).movie_rating == "up" || current_user.ratings.find_by(post_id: m.id).movie_rating.nil?
            = link_to "-", {:controller => "movies", :action => "down_vote", :id => m.id}, method: :post, class: "btn btn-default"
        - else     
          = link_to "+", {:controller => "movies", :action => "up_vote", :id => m.id}, method: :post, class: "btn btn-default"
          = link_to "-", {:controller => "movies", :action => "down_vote", :id => m.id}, method: :post, class: "btn btn-default"  
    %br 
    %br
    = link_to "View", movie_path(m), class: "btn btn-info"
    %hr
.center
  .panel.panel-default
    = will_paginate @movies

app/views/movies/new.html.haml
.container
  .row
    .col-md-4.col-md-offset-2.col-xs-12.col-sm-4.col-sm-offset-2
      .jumbotron

        %h1 New movie
        = bootstrap_form_for @movie do |f|
          = f.text_field :name
          = f.text_field :genre
          = f.text_field :box_office
          = f.text_area :desc
          = f.text_field :poster_url
          = f.submit "Create"

app/views/movies/review_list.html.haml
.center
  .panel.panel-default
    = will_paginate @reviews

- if !@reviews.empty?
  %h1 
    Reviews
  %table.table.table-hover
    %tr
      %th
        Title
      %th  
        Rating
      %th
        Comments      
    - @reviews.each do |r|
      %tr
        %td
          = link_to "#{r.title}", review_path(r)
        %td
          = r.rating        
        %td
          = r.comments.count  

app/views/movies/show.html.haml
%h1.center
  = @movie.name
  - if current_user
    - if current_user.admin?
      .btn-group
        = link_to "EDIT", edit_movie_path(@movie), class: "btn btn-default"
        = link_to "DEL", @movie, method: :delete, class: "btn btn-danger"

.col-md-6.center
  = image_tag(@movie.poster_url, size: "280x400")

.col-md-6
  %p
    %b
      Genre:
    = @movie.genre
  %p
    %b
      Box office:
    = "#{@movie.box_office}" + "$"
  %p
    %b
      Users score:
    = @movie.total_ball      
  %h3 Desctiption:
  = @movie.desc
  %hr

- if current_user
  - if current_user.admin?
    .col-md-3.form-inline
      = form_tag actor_search_list_path, :method => "get" do
        = text_field_tag :actor_name, nil, placeholder: 'Actor name', size: 15, class: "form-control"
        = hidden_field_tag :movie_id, @movie.id
        = submit_tag "Add", class: "btn btn-info"
    .col-md-3
      - if current_user
        = link_to "Add review", {:controller => "reviews", :action => "new", :movie_id => @movie.id}, class: "btn btn-info"

.col-md-12
  .col-md-6
    %hr
    %b
      Actors:
      %br
      %br
    - @actors.each do |a|
      %table.table-hover
      %tr
        %td= image_tag(a.photo_url, size: "70x100") 
        %td= link_to "#{a.name}", actor_path(a)
        %br
        - if current_user
          - if current_user.admin?
            = link_to "del", {:controller => "movies", :action => "delete_actor", :actor_id => a.id}, method: :delete
        %br
    = link_to "Full list", actor_list_path(@movie.id)    
  - if @reviews            
    .col-md-6
      %hr
      %b
        Reviews:
        %br
      - @reviews.each do |r|
        %p.list
          %h3= link_to "#{r.title}", actor_path(r)
      = link_to "Full list", review_list_path(@movie.id)              