config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#main'

  resources :articles
  resources :movies
  resources :actors
  resources :reviews
  resources :comments

  post 'actors/:id' => 'actors#add_movie', as: :add_movie

  delete 'actors/delete_movie/:id' => 'actors#delete_movie', as: :delete_movie

  post 'movies/:id' => 'movies#add_actor'

  delete 'movies/delete_actor/:id' => 'movies#delete_actor', as: :delete_actor

  post 'articles/up_vote/:id' => 'articles#up_vote'
  post 'articles/down_vote/:id' => 'articles#down_vote'

  post 'movies/up_vote/:id' => 'movies#up_vote'
  post 'movies/down_vote/:id' => 'movies#down_vote'

  post 'reviews/up_vote' => 'reviews#up_vote'
  post 'reviews/down_vote' => 'reviews#down_vote'

  get 'search' => 'search#search', as: :search

  get 'search_movie_list' => 'actors#movie_select_list', as: :movie_search_list
  get 'search_actor_list' => 'movies#actor_select_list', as: :actor_search_list

  get 'movie_list/:id' => 'actors#movie_list', as: :movie_list
  get 'actor_list/:id' => 'movies#actor_list', as: :actor_list
  get 'review_list/:id' => 'movies#review_list', as: :review_list
  get 'comment_list/:id' => 'comments#comments_list', as: :comment_list

  get '/:anything', to: "application#error_404", constraints: { anything: /.*/ }

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  has_and_belongs_to_many :movies, -> { uniq }, dependent: :destroy

  validates :name, :age, :photo_url, presence: true

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments, :dependent => :destroy

  validates :title, :body, :img_url, presence: true

end

app/models/article_rating.rb
class ArticleRating < ActiveRecord::Base

  belongs_to :user

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :article
  belongs_to :review

  validates :body, presence: true


end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :actors, -> { uniq }, dependent: :destroy

  validates :name, :genre, :box_office, :desc, :poster_url, presence: true

  def calculate_ball

	  	r_count = 0
	  	reviews.map {|r| r_count+=1 } 
		total_ball = reviews.map(&:total_ball).inject(:+) 
			
		if total_ball	
			total_ball = total_ball / r_count
		end
			
  end

end

app/models/movie_rating.rb
class MovieRating < ActiveRecord::Base

  belongs_to :user

end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :users

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie
  has_many :comments, dependent: :destroy

  validates :title, :body, presence: true

end

app/models/review_rating.rb
class ReviewRating < ActiveRecord::Base

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, -> {uniq}, dependent: :destroy
  has_many :ratings, dependent: :destroy

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/artcile_helper.rb
module ArtcileHelper
end

app/helpers/artciles_helper.rb
module ArtcilesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Cinema
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  -#  Nav panel
  .container
    .navbar.navbar-default
      .navbar-header
        %button.navbar-toggle{"data-toggle" => "collapse", "data-target" => "#drop-menu"}
          %span.sr-only Toggle nav
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-brand
          = link_to "Flumen", root_path
      .collapse.navbar-collapse#drop-menu
        %ul.nav.navbar-nav
          %li
            = link_to "Actors", actors_path
          %li.dropdown
            = link_to "Movies", movies_path
            -#%a.dropdown-toggle{"data-toggle" => "dropdown", "role" => "button", :url => "#{movies_path}"}
              Movies
              .caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  %a Actions
                %li
                  %a Thrillers
                %li
                  %a Comedies
                %li.divider
                %li
                  %a Full list
          %li
            = link_to "News", root_path
          %li
            = link_to "Reviews", reviews_path
        %ul.user-info.nav.navbar-nav.navbar-right
        .center.search
          = form_tag search_path, method: :get do
            .form-inline
              = text_field_tag :search, "", class: "form-control"
              = submit_tag "Search", class: "btn btn-default"

              
  %body
    -#.center.notice
    -#  = notice if notice
    -#.center.alert
    -#  = alert if alert

    .container
      .col-md-8.col-sm-8.col-xs-12#content
        .breadcrumb
          = render_breadcrumbs
        -if flash[:success] 
          .alert.alert-success    
            = flash[:success]
        -if flash[:error] 
          .alert.alert-warning    
            = flash[:error]    
          
        = yield

      -#USER PANEL
      .col-md-4.col-sm-4.col-xs-12
        .panel.panel-default
          .panel-heading.center User info
          .panel-body.cute-body
            - if user_signed_in?
              - if current_user.admin?
                = render partial: "articles/admin_panel"
              - else
                = render partial: "articles/user_panel"
              = link_to "Exit", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign in", new_user_session_path
              %li
                = link_to "Sign up", new_user_registration_path
        .panel.panel-default
          .panel-heading.center
            Posters
          .panel-body
            #myCar.carousel.slide{"data-ride" => "carousel"}

              -#Slider indicator
              %ol.carousel-indicators
                %li.active{"data-target" => "#myCar", "data-slide-to" => "0"}
                %li{"data-target" => "#myCar", "data-slide-to" => "1"}
                %li{"data-target" => "#myCar", "data-slide-to" => "2"}
                %li{"data-target" => "#myCar", "data-slide-to" => "3"}

              -#Slides
              - if Movie.first
                .carousel-inner
                  .item.active
                    = image_tag(Movie.first.poster_url)
                  - Movie.last(3).each do |m|
                    .item
                      = image_tag(m.poster_url)

              -#Slider arrows
              %a.left.carousel-control{:role => "button", :href => "#myCar", "data-slide" => "prev"}
                .glyphicon.glyphicon-chevron-left

              %a.right.carousel-control{:role => "button", :href => "#myCar", "data-slide" => "next"}
                .glyphicon.glyphicon-chevron-right
        #accordion.panel-group
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a{:href => "#collapse-1", "data-parent" => "#accordion", "data-toggle" => "collapse"}
                  Top rated movie
            #collapse-1.panel-collapse.collapse.in
              .panel-body
                %ul
                  - Movie.order('rating DESC').limit(3).each do |m|
                    %li
                      %h1#text-father1 
                        = m.name
                      %p
                        #text1
                          Tohe first text editors were "line editors" oriented to teleprinter- or typewriter-style terminals without displays...
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a{:href => "#collapse-2", "data-parent" => "#accordion", "data-toggle" => "collapse"}
                  Top rated article
            #collapse-2.panel-collapse.collapse
              .panel-body
                %ul
                  - Article.order('rating DESC').limit(3).each do |a|
                    %li
                      %h1 
                        = a.title
                      %p The first text editors were "line editors" oriented to teleprinter- or typewriter-style terminals without displays...
          .panel.panel-default
            .panel-heading
              %h4.panel-title
                %a{:href => "#collapse-3", "data-parent" => "#accordion", "data-toggle" => "collapse"}
                  Top rated reviews 
            #collapse-3.panel-collapse.collapse
              .panel-body
                %ul
                  - Review.order('rating DESC').limit(3).each do |r|
                    %li
                      %h1 
                        = r.title
                      %p The first text editors were "line editors" oriented to teleprinter- or typewriter-style terminals without displays...
      

    .footer.center.col-md-12
      Flumen © 2015
      %br
      Oleg Makarenko